apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ijx5x5zkp-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ijx5x5zkp-python 
  name: ijx5x5zkp-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ijx5x5zkp-python 
